"""
text_cleaner.py
Modular text preprocessing and normalization pipeline for resumes and job descriptions.
Cleans raw extracted text, handles Unicode ligatures, normalizes whitespace,
and prepares text for NLP entity extraction and TF-IDF similarity.
"""

import re
import string
from typing import List

# English stopwords fallback in case NLTK corpus is unavailable
FALLBACK_STOPWORDS = {
    "a", "about", "above", "after", "again", "against", "all", "am", "an", "and",
    "any", "are", "aren't", "as", "at", "be", "because", "been", "before", "being",
    "below", "between", "both", "but", "by", "can't", "cannot", "could", "couldn't",
    "did", "didn't", "do", "does", "doesn't", "doing", "don't", "down", "during",
    "each", "few", "for", "from", "further", "had", "hadn't", "has", "hasn't",
    "have", "haven't", "having", "he", "he'd", "he'll", "he's", "her", "here",
    "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i",
    "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "isn't", "it", "it's",
    "its", "itself", "let's", "me", "more", "most", "mustn't", "my", "myself",
    "no", "nor", "not", "of", "off", "on", "once", "only", "or", "other", "ought",
    "our", "ours", "ourselves", "out", "over", "own", "same", "shan't", "she",
    "she'd", "she'll", "she's", "should", "shouldn't", "so", "some", "such",
    "than", "that", "that's", "the", "their", "theirs", "them", "themselves",
    "then", "there", "there's", "these", "they", "they'd", "they'll", "they're",
    "they've", "this", "those", "through", "to", "too", "under", "until", "up",
    "very", "was", "wasn't", "we", "we'd", "we'll", "we're", "we've", "were",
    "weren't", "what", "what's", "when", "when's", "where", "where's", "which",
    "while", "who", "who's", "whom", "why", "why's", "with", "won't", "would",
    "wouldn't", "you", "you'd", "you'll", "you're", "you've", "your", "yours",
    "yourself", "yourselves"
}

try:
    from nltk.corpus import stopwords
    STOPWORDS = set(stopwords.words("english"))
except Exception:
    STOPWORDS = FALLBACK_STOPWORDS

# Common ligatures generated by LaTeX and PDF typography
UNICODE_LIGATURES = {
    "\ufb00": "ff",
    "\ufb01": "fi",
    "\ufb02": "fl",
    "\ufb03": "ffi",
    "\ufb04": "ffl",
    "\ufb05": "ft",
    "\ufb06": "st",
    "\u2010": "-",
    "\u2011": "-",
    "\u2012": "-",
    "\u2013": "-",
    "\u2014": "-",
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2022": " ",
    "\u25cf": " ",
    "\u25aa": " ",
    "\u25a0": " ",
    "\u00a0": " ",  # Non-breaking space
}


def clean_unicode_ligatures(text: str) -> str:
    """Replaces typography ligatures, fancy quotes, and dashes with standard ASCII equivalents."""
    if not text:
        return ""
    for char, replacement in UNICODE_LIGATURES.items():
        text = text.replace(char, replacement)
    # Remove control characters and zero-width spaces
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f\u200b-\u200f]", "", text)
    return text


def clean_text(text: str) -> str:
    """
    Cleans raw resume text for readable presentation and NLP analysis:
    - Normalizes Unicode ligatures
    - Standardizes line breaks and whitespace
    - Replaces bullet points with clean indentation
    - Preserves email, phone, links, and programming symbols (C++, C#, .NET, CI/CD)
    """
    if not text:
        return ""

    # Normalize ligatures and special symbols
    text = clean_unicode_ligatures(text)

    # Normalize bullet markers
    text = re.sub(r"[\t\r]+", " ", text)
    text = re.sub(r"[•●▪◆★✓✔*]\s*", "\n- ", text)

    # Collapse multiple consecutive empty lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Clean horizontal whitespace on each line
    lines = [re.sub(r"[ ]+", " ", line).strip() for line in text.split("\n")]
    text = "\n".join(lines).strip()

    return text


def clean_for_nlp(text: str) -> str:
    """
    Deep cleaning for TF-IDF vectorization and word matching:
    - Lowercases text
    - Removes URLs and web addresses
    - Removes punctuation while preserving technical tokens (+, #, -, /)
    - Collapses to single line
    """
    if not text:
        return ""

    text = clean_unicode_ligatures(text)
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b", " ", text)

    # Normalize bullet marks and dashes
    text = re.sub(r"[•●▪◆★✓✔\-\–\—]", " ", text)

    # Collapse multi-spaces
    text = re.sub(r"\s+", " ", text).strip()
    return text


def tokenize_words(text: str, lower: bool = True) -> List[str]:
    """Tokenizes text into words while keeping tech identifiers intact (e.g., C++, C#, CI/CD)."""
    if not text:
        return []
    if lower:
        text = text.lower()
    tokens = re.findall(r"\b[a-zA-Z0-9\+\#\./\-]+\b", text)
    return tokens


def remove_stopwords(tokens: List[str]) -> List[str]:
    """Filters out common English stopwords from a token list."""
    return [t for t in tokens if t.lower() not in STOPWORDS and len(t) > 1]


def extract_sentences(text: str) -> List[str]:
    """Splits resume text into bullet point statements or sentences."""
    if not text:
        return []
    lines = re.split(r"[\n\r•●▪\.]+", text)
    cleaned = [line.strip() for line in lines if len(line.strip()) > 10]
    return cleaned
