[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#111827"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
